name: course_feedback
description: Simple feedback form posting to Google Apps Script
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  # âœ… Use only one firebase_core (keep this)
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  intl: ^0.20.2
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/intro.mp4
    - assets/logo.webp
