name: course_feedback
description: Simple feedback form posting to Google Apps Script
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.4   # ⬅️ add this
  http: ^1.2.0
  intl: ^0.20.2
  video_player: ^2.9.2
  connectivity_plus: ^6.0.5
  hive_flutter: ^1.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 

flutter:
  uses-material-design: true
  assets:
    - assets/intro.mp4
    - assets/logo.webp
